/**
 * Indicatifs téléphoniques internationaux.
 * Congo-Brazzaville (+242) en premier par défaut.
 */
export interface CountryCodeOption {
  code: string;
  label: string;
}

const CONGO_BRAZZAVILLE: CountryCodeOption = {
  code: "+242",
  label: "Congo (Brazzaville)",
};

const REST: CountryCodeOption[] = [
  { code: "+93", label: "Afghanistan" },
  { code: "+355", label: "Albanie" },
  { code: "+213", label: "Algérie" },
  { code: "+244", label: "Angola" },
  { code: "+54", label: "Argentine" },
  { code: "+374", label: "Arménie" },
  { code: "+61", label: "Australie" },
  { code: "+43", label: "Autriche" },
  { code: "+994", label: "Azerbaïdjan" },
  { code: "+973", label: "Bahreïn" },
  { code: "+880", label: "Bangladesh" },
  { code: "+375", label: "Biélorussie" },
  { code: "+32", label: "Belgique" },
  { code: "+229", label: "Bénin" },
  { code: "+591", label: "Bolivie" },
  { code: "+387", label: "Bosnie-Herzégovine" },
  { code: "+267", label: "Botswana" },
  { code: "+55", label: "Brésil" },
  { code: "+359", label: "Bulgarie" },
  { code: "+226", label: "Burkina Faso" },
  { code: "+257", label: "Burundi" },
  { code: "+855", label: "Cambodge" },
  { code: "+237", label: "Cameroun" },
  { code: "+1", label: "Canada" },
  { code: "+238", label: "Cap-Vert" },
  { code: "+235", label: "Tchad" },
  { code: "+56", label: "Chili" },
  { code: "+86", label: "Chine" },
  { code: "+57", label: "Colombie" },
  { code: "+269", label: "Comores" },
  { code: "+243", label: "Congo (RDC)" },
  { code: "+506", label: "Costa Rica" },
  { code: "+385", label: "Croatie" },
  { code: "+53", label: "Cuba" },
  { code: "+357", label: "Chypre" },
  { code: "+420", label: "République tchèque" },
  { code: "+45", label: "Danemark" },
  { code: "+253", label: "Djibouti" },
  { code: "+593", label: "Équateur" },
  { code: "+20", label: "Égypte" },
  { code: "+503", label: "Salvador" },
  { code: "+240", label: "Guinée équatoriale" },
  { code: "+291", label: "Érythrée" },
  { code: "+372", label: "Estonie" },
  { code: "+251", label: "Éthiopie" },
  { code: "+358", label: "Finlande" },
  { code: "+33", label: "France" },
  { code: "+241", label: "Gabon" },
  { code: "+220", label: "Gambie" },
  { code: "+995", label: "Géorgie" },
  { code: "+49", label: "Allemagne" },
  { code: "+233", label: "Ghana" },
  { code: "+30", label: "Grèce" },
  { code: "+224", label: "Guinée" },
  { code: "+245", label: "Guinée-Bissau" },
  { code: "+592", label: "Guyana" },
  { code: "+509", label: "Haïti" },
  { code: "+504", label: "Honduras" },
  { code: "+852", label: "Hong Kong" },
  { code: "+36", label: "Hongrie" },
  { code: "+354", label: "Islande" },
  { code: "+91", label: "Inde" },
  { code: "+62", label: "Indonésie" },
  { code: "+98", label: "Iran" },
  { code: "+964", label: "Irak" },
  { code: "+353", label: "Irlande" },
  { code: "+972", label: "Israël" },
  { code: "+39", label: "Italie" },
  { code: "+225", label: "Côte d'Ivoire" },
  { code: "+81", label: "Japon" },
  { code: "+962", label: "Jordanie" },
  { code: "+7", label: "Kazakhstan" },
  { code: "+254", label: "Kenya" },
  { code: "+965", label: "Koweït" },
  { code: "+996", label: "Kirghizistan" },
  { code: "+856", label: "Laos" },
  { code: "+371", label: "Lettonie" },
  { code: "+961", label: "Liban" },
  { code: "+266", label: "Lesotho" },
  { code: "+231", label: "Liberia" },
  { code: "+218", label: "Libye" },
  { code: "+423", label: "Liechtenstein" },
  { code: "+370", label: "Lituanie" },
  { code: "+352", label: "Luxembourg" },
  { code: "+261", label: "Madagascar" },
  { code: "+265", label: "Malawi" },
  { code: "+60", label: "Malaisie" },
  { code: "+223", label: "Mali" },
  { code: "+356", label: "Malte" },
  { code: "+222", label: "Mauritanie" },
  { code: "+230", label: "Maurice" },
  { code: "+52", label: "Mexique" },
  { code: "+373", label: "Moldavie" },
  { code: "+377", label: "Monaco" },
  { code: "+976", label: "Mongolie" },
  { code: "+382", label: "Monténégro" },
  { code: "+212", label: "Maroc" },
  { code: "+258", label: "Mozambique" },
  { code: "+95", label: "Myanmar" },
  { code: "+264", label: "Namibie" },
  { code: "+674", label: "Nauru" },
  { code: "+977", label: "Népal" },
  { code: "+31", label: "Pays-Bas" },
  { code: "+64", label: "Nouvelle-Zélande" },
  { code: "+505", label: "Nicaragua" },
  { code: "+227", label: "Niger" },
  { code: "+234", label: "Nigeria" },
  { code: "+47", label: "Norvège" },
  { code: "+968", label: "Oman" },
  { code: "+256", label: "Ouganda" },
  { code: "+998", label: "Ouzbékistan" },
  { code: "+92", label: "Pakistan" },
  { code: "+680", label: "Palaos" },
  { code: "+970", label: "Palestine" },
  { code: "+507", label: "Panama" },
  { code: "+675", label: "Papouasie-Nouvelle-Guinée" },
  { code: "+595", label: "Paraguay" },
  { code: "+51", label: "Pérou" },
  { code: "+63", label: "Philippines" },
  { code: "+48", label: "Pologne" },
  { code: "+351", label: "Portugal" },
  { code: "+974", label: "Qatar" },
  { code: "+40", label: "Roumanie" },
  { code: "+250", label: "Rwanda" },
  { code: "+966", label: "Arabie saoudite" },
  { code: "+221", label: "Sénégal" },
  { code: "+381", label: "Serbie" },
  { code: "+248", label: "Seychelles" },
  { code: "+232", label: "Sierra Leone" },
  { code: "+65", label: "Singapour" },
  { code: "+421", label: "Slovaquie" },
  { code: "+386", label: "Slovénie" },
  { code: "+252", label: "Somalie" },
  { code: "+27", label: "Afrique du Sud" },
  { code: "+211", label: "Soudan du Sud" },
  { code: "+34", label: "Espagne" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+249", label: "Soudan" },
  { code: "+597", label: "Suriname" },
  { code: "+268", label: "Eswatini" },
  { code: "+46", label: "Suède" },
  { code: "+41", label: "Suisse" },
  { code: "+963", label: "Syrie" },
  { code: "+886", label: "Taïwan" },
  { code: "+992", label: "Tadjikistan" },
  { code: "+255", label: "Tanzanie" },
  { code: "+66", label: "Thaïlande" },
  { code: "+228", label: "Togo" },
  { code: "+676", label: "Tonga" },
  { code: "+216", label: "Tunisie" },
  { code: "+993", label: "Turkménistan" },
  { code: "+90", label: "Turquie" },
  { code: "+380", label: "Ukraine" },
  { code: "+971", label: "Émirats arabes unis" },
  { code: "+44", label: "Royaume-Uni" },
  { code: "+1", label: "États-Unis" },
  { code: "+598", label: "Uruguay" },
  { code: "+379", label: "Vatican" },
  { code: "+58", label: "Venezuela" },
  { code: "+84", label: "Viêt Nam" },
  { code: "+967", label: "Yémen" },
  { code: "+260", label: "Zambie" },
  { code: "+263", label: "Zimbabwe" },
];

/** Liste des indicatifs : Congo-Brazzaville en premier, puis reste du monde (ordre alphabétique par label). */
export const COUNTRY_PHONE_CODES: CountryCodeOption[] = [
  CONGO_BRAZZAVILLE,
  ...REST.sort((a, b) => a.label.localeCompare(b.label)),
];

export const DEFAULT_COUNTRY_CODE = "+242";
